const mongoose = require('mongoose');
const Course = require('./models/Course');
const dotenv = require("dotenv");

dotenv.config();

const courses = [
  // Part I - common foundational courses
  {
    code: 'MTH 101',
    title: 'Elementary Mathematics I',
    level: 'Part I',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: [],
    isElective: false,
    description: 'Basic calculus and algebra fundamentals.',
    semester: 'First',
  },
  {
    code: 'MTH 102',
    title: 'Elementary Mathematics II',
    level: 'Part I',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['MTH 101'],
    isElective: false,
    description: 'Continuation of elementary mathematics (sequences, series, introductory calculus).',
    semester: 'Second',
  },
  {
    code: 'MTH 104',
    title: 'Basic Mathematics',
    level: 'Part I',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 2,
    prerequisites: [],
    isElective: false,
    description: 'Fundamental mathematical techniques for science and engineering.',
    semester: 'First',
  },
  {
    code: 'PHY 101',
    title: 'Physics I',
    level: 'Part I',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: [],
    isElective: false,
    description: 'Mechanics, waves and basic physical principles.',
    semester: 'First',
  },
  {
    code: 'PHY 102',
    title: 'Physics II',
    level: 'Part I',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['PHY 101'],
    isElective: false,
    description: 'Electricity, magnetism and optics.',
    semester: 'Second',
  },
  {
    code: 'CHM 101',
    title: 'General Chemistry I',
    level: 'Part I',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: [],
    isElective: false,
    description: 'Introductory general chemistry.',
    semester: 'First',
  },
  {
    code: 'CHM 102',
    title: 'General Chemistry II',
    level: 'Part I',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CHM 101'],
    isElective: false,
    description: 'Continuation of general chemistry.',
    semester: 'Second',
  },
  {
    code: 'CHM 103',
    title: 'Chemistry Laboratory I',
    level: 'Part I',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 1,
    prerequisites: ['CHM 101'],
    isElective: false,
    description: 'Practical chemistry experiments.',
    semester: 'First',
  },
  {
    code: 'CHM 104',
    title: 'Chemistry Laboratory II',
    level: 'Part I',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 1,
    prerequisites: ['CHM 102'],
    isElective: false,
    description: 'Continuation of chemistry laboratory.',
    semester: 'Second',
  },
  {
    code: 'CSC 101',
    title: 'Introduction to Computer Science',
    level: 'Part I',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Science with Economics', 'Computer Engineering'],
    credits: 3,
    prerequisites: [],
    isElective: false,
    description: 'Overview of computing, history, and basic concepts.',
    semester: 'First',
  },
  {
    code: 'CSC 102',
    title: 'Computing Fundamentals / Programming Fundamentals',
    level: 'Part I',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 2,
    prerequisites: ['CSC 101'],
    isElective: false,
    description: 'Introduction to programming and basic computing tools.',
    semester: 'Second',
  },
  {
    code: 'TPD 101',
    title: 'Technical and Professional Development I',
    level: 'Part I',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 1,
    prerequisites: [],
    isElective: false,
    description: 'Professional skills development.',
    semester: 'First',
  },
  {
    code: 'SEO 001',
    title: 'Student Enrollment Orientation (SEO)',
    level: 'Part I',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 0,
    prerequisites: [],
    isElective: false,
    description: 'Orientation and introductory sessions.',
    semester: 'First',
  },
  {
    code: 'SER 001',
    title: 'Student Enrolment (SER)',
    level: 'Part I',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 0,
    prerequisites: [],
    isElective: false,
    description: 'Administrative orientation component.',
    semester: 'First',
  },

  // Part II - common and program-specific
  {
    code: 'CSC 201',
    title: 'Computer Programming I',
    level: 'Part II',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Science with Economics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CSC 102'],
    isElective: false,
    description: 'Structured programming and problem solving.',
    semester: 'First',
  },
  {
    code: 'CSC 202',
    title: 'Computer Programming II',
    level: 'Part II',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CSC 201'],
    isElective: false,
    description: 'Object-oriented and advanced programming topics.',
    semester: 'Second',
  },
  {
    code: 'CPE 203',
    title: 'Digital Logic Design',
    level: 'Part II',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: [],
    isElective: false,
    description: 'Boolean algebra and combinational/sequential logic circuits.',
    semester: 'First',
  },
  {
    code: 'CPE 204',
    title: 'Circuits and Systems I',
    level: 'Part II',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: [],
    isElective: false,
    description: 'Circuit theory fundamentals.',
    semester: 'Second',
  },
  {
    code: 'CPE 206',
    title: 'Introduction to Computer Engineering',
    level: 'Part II',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 2,
    prerequisites: [],
    isElective: false,
    description: 'Overview of computer engineering principles.',
    semester: 'First',
  },
  {
    code: 'MTH 201',
    title: 'Calculus I',
    level: 'Part II',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['MTH 101'],
    isElective: false,
    description: 'Differential and integral calculus.',
    semester: 'First',
  },
  {
    code: 'MTH 202',
    title: 'Calculus II',
    level: 'Part II',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['MTH 201'],
    isElective: false,
    description: 'Further topics in calculus including series and multivariable basics.',
    semester: 'Second',
  },
  {
    code: 'MTH 205',
    title: 'Linear Algebra',
    level: 'Part II',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 3,
    prerequisites: ['MTH 101'],
    isElective: false,
    description: 'Vectors, matrices, and linear transformations.',
    semester: 'Second',
  },
  {
    code: 'STT 201',
    title: 'Introductory Statistics I',
    level: 'Part II',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 2,
    prerequisites: [],
    isElective: false,
    description: 'Descriptive statistics and probability basics.',
    semester: 'First',
  },
  {
    code: 'STT 202',
    title: 'Introductory Statistics II',
    level: 'Part II',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 2,
    prerequisites: ['STT 201'],
    isElective: false,
    description: 'Inferential statistics and hypothesis testing.',
    semester: 'Second',
  },

  // Economics courses (where present in table)
  {
    code: 'ECN 201',
    title: 'Introduction to Microeconomics',
    level: 'Part II',
    programs: ['Computer Science with Mathematics', 'Computer Science with Economics'],
    credits: 2,
    prerequisites: [],
    isElective: false,
    description: 'Principles of microeconomics.',
    semester: 'First',
  },
  {
    code: 'ECN 202',
    title: 'Introduction to Macroeconomics',
    level: 'Part II',
    programs: ['Computer Science with Mathematics', 'Computer Science with Economics'],
    credits: 2,
    prerequisites: [],
    isElective: false,
    description: 'Principles of macroeconomics.',
    semester: 'Second',
  },
  {
    code: 'ECN 203',
    title: 'Mathematical Economics I',
    level: 'Part II',
    programs: ['Computer Science with Mathematics'],
    credits: 2,
    prerequisites: ['MTH 201'],
    isElective: false,
    description: 'Mathematical methods applied to economic models.',
    semester: 'First',
  },
  {
    code: 'ECN 204',
    title: 'Mathematical Economics II',
    level: 'Part II',
    programs: ['Computer Science with Mathematics'],
    credits: 2,
    prerequisites: ['ECN 203'],
    isElective: false,
    description: 'Continuation of mathematical economics.',
    semester: 'Second',
  },

  // Mechanical / Engineering support courses for Computer Engineering
  {
    code: 'MEE 203',
    title: 'Engineering Workshop I',
    level: 'Part II',
    programs: ['Computer Engineering'],
    credits: 2,
    prerequisites: [],
    isElective: false,
    description: 'Practical engineering workshop skills.',
    semester: 'First',
  },
  {
    code: 'MEE 204',
    title: 'Engineering Workshop II',
    level: 'Part II',
    programs: ['Computer Engineering'],
    credits: 2,
    prerequisites: ['MEE 203'],
    isElective: false,
    description: 'Continuation of workshop practice.',
    semester: 'Second',
  },
  {
    code: 'MEE 205',
    title: 'Mechanics I',
    level: 'Part II',
    programs: ['Computer Engineering'],
    credits: 2,
    prerequisites: [],
    isElective: false,
    description: 'Statics and basic mechanics.',
    semester: 'First',
  },
  {
    code: 'MEE 206',
    title: 'Mechanics II',
    level: 'Part II',
    programs: ['Computer Engineering'],
    credits: 2,
    prerequisites: ['MEE 205'],
    isElective: false,
    description: 'Dynamics and applied mechanics.',
    semester: 'Second',
  },
  {
    code: 'CHE 201',
    title: 'Physical Chemistry for Engineers',
    level: 'Part II',
    programs: ['Computer Engineering'],
    credits: 2,
    prerequisites: [],
    isElective: false,
    description: 'Chemical principles applied to engineering problems.',
    semester: 'First',
  },
  {
    code: 'EEE 201',
    title: 'Basic Electrical Engineering I',
    level: 'Part II',
    programs: ['Computer Engineering'],
    credits: 3,
    prerequisites: [],
    isElective: false,
    description: 'Fundamentals of electrical circuits and systems.',
    semester: 'First',
  },
  {
    code: 'EEE 202',
    title: 'Basic Electrical Engineering II',
    level: 'Part II',
    programs: ['Computer Engineering'],
    credits: 3,
    prerequisites: ['EEE 201'],
    isElective: false,
    description: 'Continuation of electrical engineering fundamentals.',
    semester: 'Second',
  },
  {
    code: 'EEE 291',
    title: 'Electrical Laboratory I',
    level: 'Part II',
    programs: ['Computer Engineering'],
    credits: 1,
    prerequisites: ['EEE 201'],
    isElective: false,
    description: 'Practical electrical engineering experiments.',
    semester: 'First',
  },
  {
    code: 'EEE 292',
    title: 'Electrical Laboratory II',
    level: 'Part II',
    programs: ['Computer Engineering'],
    credits: 1,
    prerequisites: ['EEE 202'],
    isElective: false,
    description: 'Continuation of electrical laboratory.',
    semester: 'Second',
  },
  {
    code: 'AGE 202',
    title: 'Engineering Geology',
    level: 'Part II',
    programs: ['Computer Engineering'],
    credits: 2,
    prerequisites: [],
    isElective: false,
    description: 'Geological concepts relevant to engineering.',
    semester: 'Second',
  },
  {
    code: 'CVE 202',
    title: 'Engineering Drawing',
    level: 'Part II',
    programs: ['Computer Engineering'],
    credits: 2,
    prerequisites: [],
    isElective: false,
    description: 'Technical drawing and CAD basics.',
    semester: 'Second',
  },

  // Part III - Computer Science core and variants
  {
    code: 'CPE 301',
    title: 'Computer Architecture I',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 206', 'CSC 202'],
    isElective: false,
    description: 'Organization of computer systems and instruction sets.',
    semester: 'First',
  },
  {
    code: 'CSC 302',
    title: 'Data Structures',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CSC 202'],
    isElective: false,
    description: 'Linear and non-linear data structures and algorithms.',
    semester: 'First',
  },
  {
    code: 'CSC 304',
    title: 'Algorithms I',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 3,
    prerequisites: ['CSC 302'],
    isElective: false,
    description: 'Algorithm design and complexity analysis.',
    semester: 'Second',
  },
  {
    code: 'CSC 305',
    title: 'Operating Systems I',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 3,
    prerequisites: ['CSC 302'],
    isElective: false,
    description: 'Processes, scheduling, memory and file systems.',
    semester: 'Second',
  },
  {
    code: 'CSC 306',
    title: 'Database Systems I',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CSC 302'],
    isElective: false,
    description: 'Relational models, SQL and database design.',
    semester: 'First',
  },
  {
    code: 'CSC 307',
    title: 'Software Engineering I',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CSC 301'],
    isElective: false,
    description: 'Software lifecycle, requirements, and design.',
    semester: 'Second',
  },
  {
    code: 'CSC 308',
    title: 'Computer Networks I',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 3,
    prerequisites: ['CSC 302'],
    isElective: false,
    description: 'Network models, protocols and architectures.',
    semester: 'Second',
  },
  {
    code: 'CSC 311',
    title: 'Formal Languages & Automata',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 3,
    prerequisites: ['MTH 201'],
    isElective: false,
    description: 'Formal grammars, automata and computability basics.',
    semester: 'Second',
  },
  {
    code: 'CSC 312',
    title: 'Programming Languages',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 3,
    prerequisites: ['CSC 202'],
    isElective: false,
    description: 'Language paradigms, syntax and semantics.',
    semester: 'First',
  },
  {
    code: 'CSC 315',
    title: 'Human-Computer Interaction',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 2,
    prerequisites: [],
    isElective: false,
    description: 'Design principles for user interfaces.',
    semester: 'Second',
  },
  {
    code: 'CSC 317',
    title: 'Theory of Computation',
    level: 'Part III',
    programs: ['Computer Science'],
    credits: 3,
    prerequisites: ['CSC 311'],
    isElective: false,
    description: 'Advanced topics in automata theory and computability.',
    semester: 'First',
  },
  {
    code: 'CPE 309',
    title: 'Microprocessors I',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 301'],
    isElective: false,
    description: 'Microprocessor architecture and interfacing.',
    semester: 'Second',
  },
  {
    code: 'CPE 310',
    title: 'Embedded Systems I',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 309'],
    isElective: false,
    description: 'Design of embedded hardware/software systems.',
    semester: 'Second',
  },
  {
    code: 'CPE 314',
    title: 'Logic Design II',
    level: 'Part III',
    programs: ['Computer Science'],
    credits: 2,
    prerequisites: ['CPE 203'],
    isElective: false,
    description: 'Advanced digital logic topics.',
    semester: 'First',
  },
  {
    code: 'CPE 316',
    title: 'Digital Systems Design',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 203'],
    isElective: false,
    description: 'Design and implementation of digital systems.',
    semester: 'First',
  },

  // Part III - math/econ extras
  {
    code: 'MTH 301',
    title: 'Advanced Calculus',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 3,
    prerequisites: ['MTH 201'],
    isElective: false,
    description: 'Advanced calculus topics useful in computing.',
    semester: 'First',
  },
  {
    code: 'MTH 302',
    title: 'Complex Analysis / Applied Mathematics',
    level: 'Part III',
    programs: ['Computer Science'],
    credits: 3,
    prerequisites: ['MTH 301'],
    isElective: false,
    description: 'Topics in complex variables or applied math.',
    semester: 'Second',
  },
  {
    code: 'ECN 301',
    title: 'Intermediate Microeconomics',
    level: 'Part III',
    programs: ['Computer Science with Mathematics', 'Computer Science with Economics'],
    credits: 2,
    prerequisites: ['ECN 201'],
    isElective: false,
    description: 'Consumer and producer theory and market structures.',
    semester: 'Second',
  },
  {
    code: 'ECN 302',
    title: 'Intermediate Macroeconomics',
    level: 'Part III',
    programs: ['Computer Science with Mathematics', 'Computer Science with Economics'],
    credits: 2,
    prerequisites: ['ECN 202'],
    isElective: false,
    description: 'Aggregate economic models and policy analysis.',
    semester: 'Second',
  },
  {
    code: 'ECN 313',
    title: 'Mathematical Economics II',
    level: 'Part III',
    programs: ['Computer Science with Mathematics'],
    credits: 2,
    prerequisites: ['ECN 203'],
    isElective: false,
    description: 'Advanced mathematical techniques for economics.',
    semester: 'First',
  },
  {
    code: 'ECN 314',
    title: 'Econometrics I',
    level: 'Part III',
    programs: ['Computer Science with Mathematics'],
    credits: 2,
    prerequisites: ['MTH 201', 'ECN 201'],
    isElective: false,
    description: 'Introductory econometric methods and regression.',
    semester: 'Second',
  },

  // Part III - Computer Engineering extras
  {
    code: 'EEE 301',
    title: 'Electronics I',
    level: 'Part III',
    programs: ['Computer Engineering'],
    credits: 3,
    prerequisites: ['EEE 201'],
    isElective: false,
    description: 'Analog electronics fundamentals.',
    semester: 'First',
  },
  {
    code: 'EEE 302',
    title: 'Electronics II',
    level: 'Part III',
    programs: ['Computer Engineering'],
    credits: 3,
    prerequisites: ['EEE 301'],
    isElective: false,
    description: 'Continuation of analog/digital electronics.',
    semester: 'Second',
  },
  {
    code: 'EEE 305',
    title: 'Electrical Machines I',
    level: 'Part III',
    programs: ['Computer Engineering'],
    credits: 3,
    prerequisites: [],
    isElective: false,
    description: 'Principles of electrical machines and drives.',
    semester: 'Second',
  },
  {
    code: 'MEE 303',
    title: 'Thermodynamics',
    level: 'Part III',
    programs: ['Computer Engineering'],
    credits: 2,
    prerequisites: [],
    isElective: false,
    description: 'Basic thermodynamics for engineering applications.',
    semester: 'First',
  },
  {
    code: 'CHE 305',
    title: 'Engineering Chemistry',
    level: 'Part III',
    programs: ['Computer Engineering'],
    credits: 2,
    prerequisites: [],
    isElective: false,
    description: 'Chemical principles relevant to engineering.',
    semester: 'Second',
  },
  {
    code: 'CHE 306',
    title: 'Chemical Engineering Lab',
    level: 'Part III',
    programs: ['Computer Engineering'],
    credits: 1,
    prerequisites: ['CHE 305'],
    isElective: false,
    description: 'Laboratory work in engineering chemistry.',
    semester: 'Second',
  },
  {
    code: 'AGE 302',
    title: 'Geomechanics',
    level: 'Part III',
    programs: ['Computer Engineering'],
    credits: 2,
    prerequisites: ['AGE 202'],
    isElective: false,
    description: 'Soil and rock mechanics for engineering contexts.',
    semester: 'First',
  },
  {
    code: 'MME 201',
    title: 'Materials Engineering',
    level: 'Part III',
    programs: ['Computer Engineering'],
    credits: 2,
    prerequisites: [],
    isElective: false,
    description: 'Materials properties and selection for engineering.',
    semester: 'Second',
  },

  // Part IV - Industrial training, advanced and project courses
  {
    code: 'CPE 401',
    title: 'Computer Architecture II',
    level: 'Part IV',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 301'],
    isElective: false,
    description: 'Advanced computer organization and performance.',
    semester: 'First',
  },
  {
    code: 'CSC 400',
    title: 'SIWES (Industrial Training)',
    level: 'Part IV',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 6,
    prerequisites: [],
    isElective: false,
    description: 'Industrial Attachment / Work Experience Scheme.',
    semester: 'Second',
  },
  {
    code: 'CPE 400',
    title: 'SIWES (Industrial Training)',
    level: 'Part IV',
    programs: ['Computer Engineering'],
    credits: 6,
    prerequisites: [],
    isElective: false,
    description: 'Industrial Attachment for engineering students.',
    semester: 'Second',
  },
  {
    code: 'CSC 403',
    title: 'Systems Analysis & Design',
    level: 'Part IV',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: [],
    isElective: false,
    description: 'Techniques for system specification, modelling and design.',
    semester: 'First',
  },
  {
    code: 'CSC 407',
    title: 'Advanced Operating Systems',
    level: 'Part IV',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CSC 305'],
    isElective: false,
    description: 'Advanced OS concepts including concurrency and distributed OS.',
    semester: 'Second',
  },
  {
    code: 'CPE 405',
    title: 'VLSI & Microelectronics',
    level: 'Part IV',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 316'],
    isElective: false,
    description: 'VLSI design, fabrication concepts and microelectronics.',
    semester: 'Second',
  },
  {
    code: 'CPE 409',
    title: 'Control Systems I',
    level: 'Part IV',
    programs: ['Computer Engineering'],
    credits: 3,
    prerequisites: [],
    isElective: false,
    description: 'Feedback and control theory fundamentals.',
    semester: 'First',
  },
  {
    code: 'CSC 415',
    title: 'Artificial Intelligence I',
    level: 'Part IV',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 3,
    prerequisites: ['MTH 301', 'CSC 312'],
    isElective: false,
    description: 'Foundations of AI and search methods.',
    semester: 'Second',
  },
  {
    code: 'CSC 501',
    title: 'Project I',
    level: 'Part IV',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 6,
    prerequisites: [],
    isElective: false,
    description: 'Supervised project work / research.',
    semester: 'Second',
  },
  {
    code: 'CSC 503',
    title: 'Advanced Topics in Computing',
    level: 'Part IV',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 3,
    prerequisites: [],
    isElective: false,
    description: 'Seminar-style advanced computing topics.',
    semester: 'First',
  },
  {
    code: 'CPE 509',
    title: 'Advanced Microprocessor Systems',
    level: 'Part IV',
    programs: ['Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 309'],
    isElective: false,
    description: 'Advanced microprocessor architectures and systems.',
    semester: 'Second',
  },
  {
    code: 'CPE 511',
    title: 'Advanced Embedded Systems',
    level: 'Part IV',
    programs: ['Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 310'],
    isElective: false,
    description: 'Design and optimization of embedded systems.',
    semester: 'First',
  },
  {
    code: 'CPE 517',
    title: 'Advanced Digital Systems',
    level: 'Part IV',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 316'],
    isElective: false,
    description: 'High-level digital system design and verification.',
    semester: 'First',
  },
  {
    code: 'TPD 501',
    title: 'Technical & Professional Development II',
    level: 'Part IV',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 1,
    prerequisites: ['TPD 101'],
    isElective: false,
    description: 'Advanced professional skills and ethics.',
    semester: 'First',
  },
  {
    code: 'ECN 421',
    title: 'Economics Research Project',
    level: 'Part IV',
    programs: ['Computer Science with Mathematics'],
    credits: 3,
    prerequisites: ['ECN 301'],
    isElective: false,
    description: 'Research project in economics-related topics.',
    semester: 'Second',
  },

  // Part V - advanced, electives, and capstone
  {
    code: 'CPE 502',
    title: 'Computer Systems Design II',
    level: 'Part V',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 401'],
    isElective: false,
    description: 'Advanced systems design and integration.',
    semester: 'First',
  },
  {
    code: 'CPE 506',
    title: 'Advanced VLSI',
    level: 'Part V',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 405'],
    isElective: false,
    description: 'Advanced VLSI design and verification topics.',
    semester: 'Second',
  },
  {
    code: 'CPE 504',
    title: 'Control Systems II',
    level: 'Part V',
    programs: ['Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 409'],
    isElective: false,
    description: 'Advanced control theory and applications.',
    semester: 'First',
  },
  {
    code: 'CPE 508',
    title: 'Signal Processing',
    level: 'Part V',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['MTH 201'],
    isElective: false,
    description: 'Digital signal processing principles and techniques.',
    semester: 'First',
  },
  {
    code: 'CPE 510',
    title: 'Advanced Embedded Systems II',
    level: 'Part V',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 511', 'CPE 310'],
    isElective: false,
    description: 'Advanced topics in embedded system design and optimization.',
    semester: 'Second',
  },
  {
    code: 'CPE 502',
    title: 'Computer Systems Design II (Project/Elective)',
    level: 'Part V',
    programs: ['Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 401'],
    isElective: true,
    description: 'Elective slot used by departments for advanced design topics.',
    semester: 'First',
  },
  {
    code: 'CPE 508',
    title: 'Signal Processing (Elective)',
    level: 'Part V',
    programs: ['Computer Engineering'],
    credits: 3,
    prerequisites: ['MTH 201'],
    isElective: true,
    description: 'Elective version of signal processing.',
    semester: 'First',
  },
  {
    code: 'CSC 504',
    title: 'Project II',
    level: 'Part V',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 6,
    prerequisites: ['CSC 501'],
    isElective: false,
    description: 'Final year project and dissertation.',
    semester: 'Second',
  },
  {
    code: 'CPE 506',
    title: 'Advanced VLSI (Elective)',
    level: 'Part V',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 405'],
    isElective: true,
    description: 'Elective specialization in VLSI.',
    semester: 'Second',
  },

  // Part V - elective placeholders pulled from table
  {
    code: 'CSC 514',
    title: 'Advanced Database Systems',
    level: 'Part V',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CSC 306'],
    isElective: true,
    description: 'Advanced topics in database theory and practice.',
    semester: 'First',
  },
  {
    code: 'CSC 520',
    title: 'Machine Learning',
    level: 'Part V',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 3,
    prerequisites: ['CSC 312'],
    isElective: true,
    description: 'Fundamentals of machine learning and applied models.',
    semester: 'Second',
  },
  {
    code: 'CSC 522',
    title: 'Advanced Algorithms',
    level: 'Part V',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 3,
    prerequisites: ['CSC 304'],
    isElective: true,
    description: 'Advanced algorithmic techniques and analysis.',
    semester: 'First',
  },
  {
    code: 'CSC 524',
    title: 'Advanced Software Engineering',
    level: 'Part V',
    programs: ['Computer Science', 'Computer Science with Mathematics'],
    credits: 3,
    prerequisites: ['CSC 307'],
    isElective: true,
    description: 'Advanced software architecture and project management.',
    semester: 'Second',
  },
  {
    code: 'TPD 502',
    title: 'Technical & Professional Development III',
    level: 'Part V',
    programs: ['Computer Science', 'Computer Science with Mathematics', 'Computer Engineering'],
    credits: 1,
    prerequisites: ['TPD 501'],
    isElective: false,
    description: 'Capstone professional skills development.',
    semester: 'First',
  },

  {
    code: 'CPE 316',
    title: 'Digital Systems Design',
    level: 'Part III',
    programs: ['Computer Science', 'Computer Engineering'],
    credits: 3,
    prerequisites: ['CPE 203'],
    isElective: false,
    description: 'Digital systems design and implementation.',
    semester: 'First',
  },
  {
    code: 'CPE 317',
    title: 'Capstone Systems (placeholder)',
    level: 'Part III',
    programs: ['Computer Engineering'],
    credits: 3,
    prerequisites: [],
    isElective: false,
    description: 'Capstone / special topics in systems.',
    semester: 'Second',
  },
];

async function seedCourses(options = { useExistingConnection: false, force: false }) {
  const { useExistingConnection, force } = options;
  let openedConnection = false;

  try {
    if (!useExistingConnection) {
      await mongoose.connect(process.env.MONGO_URI, {
        useNewUrlParser: true,
        useUnifiedTopology: true,
      });
      openedConnection = true;
    }

    // If not forcing, only seed when collection is empty
    const count = await Course.countDocuments();
    if (count > 0 && !force) {
      console.log(`Courses collection already has ${count} documents. Skipping seeding.`);
      return { skipped: true, existingCount: count };
    }

    if (force) {
      console.log('FORCE_SEED=true -> clearing courses collection before seeding.');
      await Course.deleteMany({});
    }

    // Insert documents in batches to avoid huge memory spikes if array is large
    if (courses.length === 0) {
      console.warn('No courses found in seed array. Nothing to insert.');
      return { inserted: 0 };
    }

    await Course.insertMany(courses, { ordered: false }); // ordered:false continues on individual errors
    const newCount = await Course.countDocuments();
    console.log(`Seeding complete. Courses collection now has ${newCount} documents.`);
    return { inserted: courses.length, newCount };
  } catch (err) {
    console.error('Error during seeding:', err);
    throw err;
  } finally {
    if (openedConnection) {
      try {
        await mongoose.connection.close();
      } catch (closeErr) {
        console.error('Error closing mongoose connection:', closeErr);
      }
    }
  }
}

module.exports = seedCourses;

// Allow running standalone: node seedCourses.js
if (require.main === module) {
  (async () => {
    try {
      const force = process.env.FORCE_SEED === 'true';
      await seedCourses({ useExistingConnection: false, force });
      console.log('Standalone seeding finished.');
      process.exit(0);
    } catch (err) {
      console.error('Standalone seeding failed:', err);
      process.exit(1);
    }
  })();
}